# Generated by scripts/gen_stubs.py: do not edit.
#
# Typed view over the default six-package BPMN model: one class per
# concrete descriptor type (Cap(prefix) + local name, e.g. bpmn:Task
# becomes BpmnTask), Literal-typed create() overloads on
# TypedBpmnModdle, and TypeGuard-typed is_a() overloads. Elements are
# created dynamically by the model factory, so these classes have no
# runtime behavior; keyword-named properties (from, import) are omitted
# (reachable via get/set). 161 types; 5 traits skipped.
# Descriptor property names stay camelCase by contract, hence the
# file-wide N815 exemption.
# ruff: noqa: N815

from typing import Any, Literal, TypeAlias, TypeGuard, overload

from bpmn_io.bpmn_moddle.bpmn_moddle import BpmnModdle
from bpmn_io.moddle.base import ModdleElement
from bpmn_io.moddle.descriptor_builder import EffectiveDescriptor

BpmnTypeName: TypeAlias = Literal[
    "bpmn:Activity",
    "bpmn:AdHocSubProcess",
    "bpmn:Artifact",
    "bpmn:Assignment",
    "bpmn:Association",
    "bpmn:Auditing",
    "bpmn:BaseElement",
    "bpmn:BoundaryEvent",
    "bpmn:BusinessRuleTask",
    "bpmn:CallActivity",
    "bpmn:CallChoreography",
    "bpmn:CallConversation",
    "bpmn:CallableElement",
    "bpmn:CancelEventDefinition",
    "bpmn:CatchEvent",
    "bpmn:Category",
    "bpmn:CategoryValue",
    "bpmn:Choreography",
    "bpmn:ChoreographyActivity",
    "bpmn:ChoreographyTask",
    "bpmn:Collaboration",
    "bpmn:CompensateEventDefinition",
    "bpmn:ComplexBehaviorDefinition",
    "bpmn:ComplexGateway",
    "bpmn:ConditionalEventDefinition",
    "bpmn:Conversation",
    "bpmn:ConversationAssociation",
    "bpmn:ConversationLink",
    "bpmn:ConversationNode",
    "bpmn:CorrelationKey",
    "bpmn:CorrelationProperty",
    "bpmn:CorrelationPropertyBinding",
    "bpmn:CorrelationPropertyRetrievalExpression",
    "bpmn:CorrelationSubscription",
    "bpmn:DataAssociation",
    "bpmn:DataInput",
    "bpmn:DataInputAssociation",
    "bpmn:DataObject",
    "bpmn:DataObjectReference",
    "bpmn:DataOutput",
    "bpmn:DataOutputAssociation",
    "bpmn:DataState",
    "bpmn:DataStore",
    "bpmn:DataStoreReference",
    "bpmn:Definitions",
    "bpmn:Documentation",
    "bpmn:EndEvent",
    "bpmn:EndPoint",
    "bpmn:Error",
    "bpmn:ErrorEventDefinition",
    "bpmn:Escalation",
    "bpmn:EscalationEventDefinition",
    "bpmn:Event",
    "bpmn:EventBasedGateway",
    "bpmn:EventDefinition",
    "bpmn:ExclusiveGateway",
    "bpmn:Expression",
    "bpmn:Extension",
    "bpmn:ExtensionAttributeDefinition",
    "bpmn:ExtensionDefinition",
    "bpmn:ExtensionElements",
    "bpmn:FlowElement",
    "bpmn:FlowElementsContainer",
    "bpmn:FlowNode",
    "bpmn:FormalExpression",
    "bpmn:Gateway",
    "bpmn:GlobalBusinessRuleTask",
    "bpmn:GlobalChoreographyTask",
    "bpmn:GlobalConversation",
    "bpmn:GlobalManualTask",
    "bpmn:GlobalScriptTask",
    "bpmn:GlobalTask",
    "bpmn:GlobalUserTask",
    "bpmn:Group",
    "bpmn:HumanPerformer",
    "bpmn:ImplicitThrowEvent",
    "bpmn:Import",
    "bpmn:InclusiveGateway",
    "bpmn:InputOutputBinding",
    "bpmn:InputOutputSpecification",
    "bpmn:InputSet",
    "bpmn:InteractionNode",
    "bpmn:Interface",
    "bpmn:IntermediateCatchEvent",
    "bpmn:IntermediateThrowEvent",
    "bpmn:ItemAwareElement",
    "bpmn:ItemDefinition",
    "bpmn:Lane",
    "bpmn:LaneSet",
    "bpmn:LinkEventDefinition",
    "bpmn:LoopCharacteristics",
    "bpmn:ManualTask",
    "bpmn:Message",
    "bpmn:MessageEventDefinition",
    "bpmn:MessageFlow",
    "bpmn:MessageFlowAssociation",
    "bpmn:Monitoring",
    "bpmn:MultiInstanceLoopCharacteristics",
    "bpmn:Operation",
    "bpmn:OutputSet",
    "bpmn:ParallelGateway",
    "bpmn:Participant",
    "bpmn:ParticipantAssociation",
    "bpmn:ParticipantMultiplicity",
    "bpmn:PartnerEntity",
    "bpmn:PartnerRole",
    "bpmn:Performer",
    "bpmn:PotentialOwner",
    "bpmn:Process",
    "bpmn:Property",
    "bpmn:ReceiveTask",
    "bpmn:Relationship",
    "bpmn:Rendering",
    "bpmn:Resource",
    "bpmn:ResourceAssignmentExpression",
    "bpmn:ResourceParameter",
    "bpmn:ResourceParameterBinding",
    "bpmn:ResourceRole",
    "bpmn:RootElement",
    "bpmn:ScriptTask",
    "bpmn:SendTask",
    "bpmn:SequenceFlow",
    "bpmn:ServiceTask",
    "bpmn:Signal",
    "bpmn:SignalEventDefinition",
    "bpmn:StandardLoopCharacteristics",
    "bpmn:StartEvent",
    "bpmn:SubChoreography",
    "bpmn:SubConversation",
    "bpmn:SubProcess",
    "bpmn:Task",
    "bpmn:TerminateEventDefinition",
    "bpmn:TextAnnotation",
    "bpmn:ThrowEvent",
    "bpmn:TimerEventDefinition",
    "bpmn:Transaction",
    "bpmn:UserTask",
    "bpmndi:BPMNDiagram",
    "bpmndi:BPMNEdge",
    "bpmndi:BPMNLabel",
    "bpmndi:BPMNLabelStyle",
    "bpmndi:BPMNPlane",
    "bpmndi:BPMNShape",
    "dc:Boolean",
    "dc:Bounds",
    "dc:Font",
    "dc:Integer",
    "dc:Point",
    "dc:Real",
    "dc:String",
    "di:Diagram",
    "di:DiagramElement",
    "di:Edge",
    "di:Extension",
    "di:Label",
    "di:LabeledEdge",
    "di:LabeledShape",
    "di:Node",
    "di:Plane",
    "di:Shape",
    "di:Style",
]

class BpmnActivity(BpmnFlowNode):
    isForCompensation: bool
    default: BpmnSequenceFlow
    ioSpecification: BpmnInputOutputSpecification
    boundaryEventRefs: list[BpmnBoundaryEvent]
    properties: list[BpmnProperty]
    dataInputAssociations: list[BpmnDataInputAssociation]
    dataOutputAssociations: list[BpmnDataOutputAssociation]
    startQuantity: int
    resources: list[BpmnResourceRole]
    completionQuantity: int
    loopCharacteristics: BpmnLoopCharacteristics

class BpmnAdHocSubProcess(BpmnSubProcess):
    completionCondition: BpmnExpression
    ordering: str
    cancelRemainingInstances: bool

class BpmnArtifact(BpmnBaseElement): ...

class BpmnAssignment(BpmnBaseElement):
    to: BpmnExpression

class BpmnAssociation(BpmnArtifact):
    associationDirection: str
    sourceRef: BpmnBaseElement
    targetRef: BpmnBaseElement

class BpmnAuditing(BpmnBaseElement): ...

class BpmnBaseElement(ModdleElement):
    id: str
    documentation: list[BpmnDocumentation]
    extensionDefinitions: list[BpmnExtensionDefinition]
    extensionElements: BpmnExtensionElements

class BpmnBoundaryEvent(BpmnCatchEvent):
    cancelActivity: bool
    attachedToRef: BpmnActivity

class BpmnBusinessRuleTask(BpmnTask):
    implementation: str

class BpmnCallActivity(BpmnActivity, BpmnInteractionNode):
    calledElement: str

class BpmnCallChoreography(BpmnChoreographyActivity):
    calledChoreographyRef: BpmnChoreography
    participantAssociations: list[BpmnParticipantAssociation]

class BpmnCallConversation(BpmnConversationNode):
    calledCollaborationRef: BpmnCollaboration
    participantAssociations: list[BpmnParticipantAssociation]

class BpmnCallableElement(BpmnRootElement):
    name: str
    ioSpecification: BpmnInputOutputSpecification
    supportedInterfaceRef: list[BpmnInterface]
    ioBinding: list[BpmnInputOutputBinding]

class BpmnCancelEventDefinition(BpmnEventDefinition): ...

class BpmnCatchEvent(BpmnEvent):
    parallelMultiple: bool
    dataOutputs: list[BpmnDataOutput]
    dataOutputAssociations: list[BpmnDataOutputAssociation]
    outputSet: BpmnOutputSet
    eventDefinitions: list[BpmnEventDefinition]
    eventDefinitionRef: list[BpmnEventDefinition]

class BpmnCategory(BpmnRootElement):
    categoryValue: list[BpmnCategoryValue]
    name: str

class BpmnCategoryValue(BpmnBaseElement):
    categorizedFlowElements: list[BpmnFlowElement]
    value: str

class BpmnChoreography(BpmnCollaboration, BpmnFlowElementsContainer): ...

class BpmnChoreographyActivity(BpmnFlowNode):
    participantRef: list[BpmnParticipant]
    initiatingParticipantRef: BpmnParticipant
    correlationKeys: list[BpmnCorrelationKey]
    loopType: str

class BpmnChoreographyTask(BpmnChoreographyActivity):
    messageFlowRef: list[BpmnMessageFlow]

class BpmnCollaboration(BpmnRootElement):
    name: str
    isClosed: bool
    participants: list[BpmnParticipant]
    messageFlows: list[BpmnMessageFlow]
    artifacts: list[BpmnArtifact]
    conversations: list[BpmnConversationNode]
    conversationAssociations: BpmnConversationAssociation
    participantAssociations: list[BpmnParticipantAssociation]
    messageFlowAssociations: list[BpmnMessageFlowAssociation]
    correlationKeys: list[BpmnCorrelationKey]
    choreographyRef: list[BpmnChoreography]
    conversationLinks: list[BpmnConversationLink]

class BpmnCompensateEventDefinition(BpmnEventDefinition):
    waitForCompletion: bool
    activityRef: BpmnActivity

class BpmnComplexBehaviorDefinition(BpmnBaseElement):
    condition: BpmnFormalExpression
    event: BpmnImplicitThrowEvent

class BpmnComplexGateway(BpmnGateway):
    activationCondition: BpmnExpression
    default: BpmnSequenceFlow

class BpmnConditionalEventDefinition(BpmnEventDefinition):
    condition: BpmnExpression

class BpmnConversation(BpmnConversationNode): ...

class BpmnConversationAssociation(BpmnBaseElement):
    innerConversationNodeRef: BpmnConversationNode
    outerConversationNodeRef: BpmnConversationNode

class BpmnConversationLink(BpmnBaseElement):
    sourceRef: BpmnInteractionNode
    targetRef: BpmnInteractionNode
    name: str

class BpmnConversationNode(BpmnInteractionNode, BpmnBaseElement):
    name: str
    participantRef: list[BpmnParticipant]
    messageFlowRefs: list[BpmnMessageFlow]
    correlationKeys: list[BpmnCorrelationKey]

class BpmnCorrelationKey(BpmnBaseElement):
    correlationPropertyRef: list[BpmnCorrelationProperty]
    name: str

class BpmnCorrelationProperty(BpmnRootElement):
    correlationPropertyRetrievalExpression: list[BpmnCorrelationPropertyRetrievalExpression]
    name: str
    type: BpmnItemDefinition

class BpmnCorrelationPropertyBinding(BpmnBaseElement):
    dataPath: BpmnFormalExpression
    correlationPropertyRef: BpmnCorrelationProperty

class BpmnCorrelationPropertyRetrievalExpression(BpmnBaseElement):
    messagePath: BpmnFormalExpression
    messageRef: BpmnMessage

class BpmnCorrelationSubscription(BpmnBaseElement):
    correlationKeyRef: BpmnCorrelationKey
    correlationPropertyBinding: list[BpmnCorrelationPropertyBinding]

class BpmnDataAssociation(BpmnBaseElement):
    sourceRef: list[BpmnItemAwareElement]
    targetRef: BpmnItemAwareElement
    transformation: BpmnFormalExpression
    assignment: list[BpmnAssignment]

class BpmnDataInput(BpmnItemAwareElement):
    name: str
    isCollection: bool
    inputSetRef: list[BpmnInputSet]
    inputSetWithOptional: list[BpmnInputSet]
    inputSetWithWhileExecuting: list[BpmnInputSet]

class BpmnDataInputAssociation(BpmnDataAssociation): ...

class BpmnDataObject(BpmnFlowElement, BpmnItemAwareElement):
    isCollection: bool

class BpmnDataObjectReference(BpmnItemAwareElement, BpmnFlowElement):
    dataObjectRef: BpmnDataObject

class BpmnDataOutput(BpmnItemAwareElement):
    name: str
    isCollection: bool
    outputSetRef: list[BpmnOutputSet]
    outputSetWithOptional: list[BpmnOutputSet]
    outputSetWithWhileExecuting: list[BpmnOutputSet]

class BpmnDataOutputAssociation(BpmnDataAssociation): ...

class BpmnDataState(BpmnBaseElement):
    name: str

class BpmnDataStore(BpmnRootElement, BpmnItemAwareElement):
    name: str
    capacity: int
    isUnlimited: bool

class BpmnDataStoreReference(BpmnItemAwareElement, BpmnFlowElement):
    dataStoreRef: BpmnDataStore

class BpmnDefinitions(BpmnBaseElement):
    name: str
    targetNamespace: str
    expressionLanguage: str
    typeLanguage: str
    imports: list[BpmnImport]
    extensions: list[BpmnExtension]
    rootElements: list[BpmnRootElement]
    diagrams: list[BpmndiBPMNDiagram]
    exporter: str
    relationships: list[BpmnRelationship]
    exporterVersion: str

class BpmnDocumentation(BpmnBaseElement):
    text: str
    textFormat: str

class BpmnEndEvent(BpmnThrowEvent): ...
class BpmnEndPoint(BpmnRootElement): ...

class BpmnError(BpmnRootElement):
    structureRef: BpmnItemDefinition
    name: str
    errorCode: str

class BpmnErrorEventDefinition(BpmnEventDefinition):
    errorRef: BpmnError

class BpmnEscalation(BpmnRootElement):
    structureRef: BpmnItemDefinition
    name: str
    escalationCode: str

class BpmnEscalationEventDefinition(BpmnEventDefinition):
    escalationRef: BpmnEscalation

class BpmnEvent(BpmnFlowNode, BpmnInteractionNode):
    properties: list[BpmnProperty]

class BpmnEventBasedGateway(BpmnGateway):
    instantiate: bool
    eventGatewayType: str

class BpmnEventDefinition(BpmnRootElement): ...

class BpmnExclusiveGateway(BpmnGateway):
    default: BpmnSequenceFlow

class BpmnExpression(BpmnBaseElement):
    body: str

class BpmnExtension(ModdleElement):
    mustUnderstand: bool
    definition: BpmnExtensionDefinition

class BpmnExtensionAttributeDefinition(ModdleElement):
    name: str
    type: str
    isReference: bool
    extensionDefinition: BpmnExtensionDefinition

class BpmnExtensionDefinition(ModdleElement):
    name: str
    extensionAttributeDefinitions: list[BpmnExtensionAttributeDefinition]

class BpmnExtensionElements(ModdleElement):
    valueRef: ModdleElement
    values: list[ModdleElement]
    extensionAttributeDefinition: BpmnExtensionAttributeDefinition

class BpmnFlowElement(BpmnBaseElement):
    name: str
    auditing: BpmnAuditing
    monitoring: BpmnMonitoring
    categoryValueRef: list[BpmnCategoryValue]

class BpmnFlowElementsContainer(BpmnBaseElement):
    laneSets: list[BpmnLaneSet]
    flowElements: list[BpmnFlowElement]

class BpmnFlowNode(BpmnFlowElement):
    incoming: list[BpmnSequenceFlow]
    outgoing: list[BpmnSequenceFlow]
    lanes: list[BpmnLane]

class BpmnFormalExpression(BpmnExpression):
    language: str
    evaluatesToTypeRef: BpmnItemDefinition

class BpmnGateway(BpmnFlowNode):
    gatewayDirection: str

class BpmnGlobalBusinessRuleTask(BpmnGlobalTask):
    implementation: str

class BpmnGlobalChoreographyTask(BpmnChoreography):
    initiatingParticipantRef: BpmnParticipant

class BpmnGlobalConversation(BpmnCollaboration): ...
class BpmnGlobalManualTask(BpmnGlobalTask): ...

class BpmnGlobalScriptTask(BpmnGlobalTask):
    scriptLanguage: str
    script: str

class BpmnGlobalTask(BpmnCallableElement):
    resources: list[BpmnResourceRole]

class BpmnGlobalUserTask(BpmnGlobalTask):
    implementation: str
    renderings: list[BpmnRendering]

class BpmnGroup(BpmnArtifact):
    categoryValueRef: BpmnCategoryValue

class BpmnHumanPerformer(BpmnPerformer): ...
class BpmnImplicitThrowEvent(BpmnThrowEvent): ...

class BpmnImport(ModdleElement):
    importType: str
    location: str
    namespace: str

class BpmnInclusiveGateway(BpmnGateway):
    default: BpmnSequenceFlow

class BpmnInputOutputBinding(ModdleElement):
    inputDataRef: BpmnInputSet
    outputDataRef: BpmnOutputSet
    operationRef: BpmnOperation

class BpmnInputOutputSpecification(BpmnBaseElement):
    dataInputs: list[BpmnDataInput]
    dataOutputs: list[BpmnDataOutput]
    inputSets: list[BpmnInputSet]
    outputSets: list[BpmnOutputSet]

class BpmnInputSet(BpmnBaseElement):
    name: str
    dataInputRefs: list[BpmnDataInput]
    optionalInputRefs: list[BpmnDataInput]
    whileExecutingInputRefs: list[BpmnDataInput]
    outputSetRefs: list[BpmnOutputSet]

class BpmnInteractionNode(ModdleElement):
    incomingConversationLinks: list[BpmnConversationLink]
    outgoingConversationLinks: list[BpmnConversationLink]

class BpmnInterface(BpmnRootElement):
    name: str
    operations: list[BpmnOperation]
    implementationRef: str

class BpmnIntermediateCatchEvent(BpmnCatchEvent): ...
class BpmnIntermediateThrowEvent(BpmnThrowEvent): ...

class BpmnItemAwareElement(BpmnBaseElement):
    itemSubjectRef: BpmnItemDefinition
    dataState: BpmnDataState

class BpmnItemDefinition(BpmnRootElement):
    itemKind: str
    structureRef: str
    isCollection: bool

class BpmnLane(BpmnBaseElement):
    name: str
    partitionElementRef: BpmnBaseElement
    partitionElement: BpmnBaseElement
    flowNodeRef: list[BpmnFlowNode]
    childLaneSet: BpmnLaneSet

class BpmnLaneSet(BpmnBaseElement):
    lanes: list[BpmnLane]
    name: str

class BpmnLinkEventDefinition(BpmnEventDefinition):
    name: str
    target: BpmnLinkEventDefinition
    source: list[BpmnLinkEventDefinition]

class BpmnLoopCharacteristics(BpmnBaseElement): ...
class BpmnManualTask(BpmnTask): ...

class BpmnMessage(BpmnRootElement):
    name: str
    itemRef: BpmnItemDefinition

class BpmnMessageEventDefinition(BpmnEventDefinition):
    messageRef: BpmnMessage
    operationRef: BpmnOperation

class BpmnMessageFlow(BpmnBaseElement):
    name: str
    sourceRef: BpmnInteractionNode
    targetRef: BpmnInteractionNode
    messageRef: BpmnMessage

class BpmnMessageFlowAssociation(BpmnBaseElement):
    innerMessageFlowRef: BpmnMessageFlow
    outerMessageFlowRef: BpmnMessageFlow

class BpmnMonitoring(BpmnBaseElement): ...

class BpmnMultiInstanceLoopCharacteristics(BpmnLoopCharacteristics):
    isSequential: bool
    behavior: str
    loopCardinality: BpmnExpression
    loopDataInputRef: BpmnItemAwareElement
    loopDataOutputRef: BpmnItemAwareElement
    inputDataItem: BpmnDataInput
    outputDataItem: BpmnDataOutput
    complexBehaviorDefinition: list[BpmnComplexBehaviorDefinition]
    completionCondition: BpmnExpression
    oneBehaviorEventRef: BpmnEventDefinition
    noneBehaviorEventRef: BpmnEventDefinition

class BpmnOperation(BpmnBaseElement):
    name: str
    inMessageRef: BpmnMessage
    outMessageRef: BpmnMessage
    errorRef: list[BpmnError]
    implementationRef: str

class BpmnOutputSet(BpmnBaseElement):
    dataOutputRefs: list[BpmnDataOutput]
    name: str
    inputSetRefs: list[BpmnInputSet]
    optionalOutputRefs: list[BpmnDataOutput]
    whileExecutingOutputRefs: list[BpmnDataOutput]

class BpmnParallelGateway(BpmnGateway): ...

class BpmnParticipant(BpmnInteractionNode, BpmnBaseElement):
    name: str
    interfaceRef: list[BpmnInterface]
    participantMultiplicity: BpmnParticipantMultiplicity
    endPointRefs: list[BpmnEndPoint]
    processRef: BpmnProcess

class BpmnParticipantAssociation(BpmnBaseElement):
    innerParticipantRef: BpmnParticipant
    outerParticipantRef: BpmnParticipant

class BpmnParticipantMultiplicity(BpmnBaseElement):
    minimum: int
    maximum: int

class BpmnPartnerEntity(BpmnRootElement):
    name: str
    participantRef: list[BpmnParticipant]

class BpmnPartnerRole(BpmnRootElement):
    name: str
    participantRef: list[BpmnParticipant]

class BpmnPerformer(BpmnResourceRole): ...
class BpmnPotentialOwner(BpmnHumanPerformer): ...

class BpmnProcess(BpmnFlowElementsContainer, BpmnCallableElement):
    processType: str
    isClosed: bool
    auditing: BpmnAuditing
    monitoring: BpmnMonitoring
    properties: list[BpmnProperty]
    laneSets: list[BpmnLaneSet]
    flowElements: list[BpmnFlowElement]
    artifacts: list[BpmnArtifact]
    resources: list[BpmnResourceRole]
    correlationSubscriptions: list[BpmnCorrelationSubscription]
    supports: list[BpmnProcess]
    definitionalCollaborationRef: BpmnCollaboration
    isExecutable: bool

class BpmnProperty(BpmnItemAwareElement):
    name: str

class BpmnReceiveTask(BpmnTask):
    implementation: str
    instantiate: bool
    operationRef: BpmnOperation
    messageRef: BpmnMessage

class BpmnRelationship(BpmnBaseElement):
    type: str
    direction: str
    source: list[ModdleElement]
    target: list[ModdleElement]

class BpmnRendering(BpmnBaseElement): ...

class BpmnResource(BpmnRootElement):
    name: str
    resourceParameters: list[BpmnResourceParameter]

class BpmnResourceAssignmentExpression(BpmnBaseElement):
    expression: BpmnExpression

class BpmnResourceParameter(BpmnBaseElement):
    name: str
    isRequired: bool
    type: BpmnItemDefinition

class BpmnResourceParameterBinding(BpmnBaseElement):
    expression: BpmnExpression
    parameterRef: BpmnResourceParameter

class BpmnResourceRole(BpmnBaseElement):
    resourceRef: BpmnResource
    resourceParameterBindings: list[BpmnResourceParameterBinding]
    resourceAssignmentExpression: BpmnResourceAssignmentExpression
    name: str

class BpmnRootElement(BpmnBaseElement): ...

class BpmnScriptTask(BpmnTask):
    scriptFormat: str
    script: str

class BpmnSendTask(BpmnTask):
    implementation: str
    operationRef: BpmnOperation
    messageRef: BpmnMessage

class BpmnSequenceFlow(BpmnFlowElement):
    isImmediate: bool
    conditionExpression: BpmnExpression
    sourceRef: BpmnFlowNode
    targetRef: BpmnFlowNode

class BpmnServiceTask(BpmnTask):
    implementation: str
    operationRef: BpmnOperation

class BpmnSignal(BpmnRootElement):
    structureRef: BpmnItemDefinition
    name: str

class BpmnSignalEventDefinition(BpmnEventDefinition):
    signalRef: BpmnSignal

class BpmnStandardLoopCharacteristics(BpmnLoopCharacteristics):
    testBefore: bool
    loopCondition: BpmnExpression
    loopMaximum: int

class BpmnStartEvent(BpmnCatchEvent):
    isInterrupting: bool

class BpmnSubChoreography(BpmnChoreographyActivity, BpmnFlowElementsContainer):
    artifacts: list[BpmnArtifact]

class BpmnSubConversation(BpmnConversationNode):
    conversationNodes: list[BpmnConversationNode]

class BpmnSubProcess(BpmnActivity, BpmnFlowElementsContainer, BpmnInteractionNode):
    triggeredByEvent: bool
    artifacts: list[BpmnArtifact]

class BpmnTask(BpmnActivity, BpmnInteractionNode): ...
class BpmnTerminateEventDefinition(BpmnEventDefinition): ...

class BpmnTextAnnotation(BpmnArtifact):
    text: str
    textFormat: str

class BpmnThrowEvent(BpmnEvent):
    dataInputs: list[BpmnDataInput]
    dataInputAssociations: list[BpmnDataInputAssociation]
    inputSet: BpmnInputSet
    eventDefinitions: list[BpmnEventDefinition]
    eventDefinitionRef: list[BpmnEventDefinition]

class BpmnTimerEventDefinition(BpmnEventDefinition):
    timeDate: BpmnExpression
    timeCycle: BpmnExpression
    timeDuration: BpmnExpression

class BpmnTransaction(BpmnSubProcess):
    protocol: str
    method: str

class BpmnUserTask(BpmnTask):
    renderings: list[BpmnRendering]
    implementation: str

class BpmndiBPMNDiagram(DiDiagram):
    plane: BpmndiBPMNPlane
    labelStyle: list[BpmndiBPMNLabelStyle]

class BpmndiBPMNEdge(DiLabeledEdge):
    label: BpmndiBPMNLabel
    bpmnElement: BpmnBaseElement
    sourceElement: DiDiagramElement
    targetElement: DiDiagramElement
    messageVisibleKind: str

class BpmndiBPMNLabel(DiLabel):
    labelStyle: BpmndiBPMNLabelStyle

class BpmndiBPMNLabelStyle(DiStyle):
    font: DcFont

class BpmndiBPMNPlane(DiPlane):
    bpmnElement: BpmnBaseElement

class BpmndiBPMNShape(DiLabeledShape):
    bpmnElement: BpmnBaseElement
    isHorizontal: bool
    isExpanded: bool
    isMarkerVisible: bool
    label: BpmndiBPMNLabel
    isMessageVisible: bool
    participantBandKind: str
    choreographyActivityShape: BpmndiBPMNShape

class DcBoolean(ModdleElement): ...

class DcBounds(ModdleElement):
    x: float
    y: float
    width: float
    height: float

class DcFont(ModdleElement):
    name: str
    size: float
    isBold: bool
    isItalic: bool
    isUnderline: bool
    isStrikeThrough: bool

class DcInteger(ModdleElement): ...

class DcPoint(ModdleElement):
    x: float
    y: float

class DcReal(ModdleElement): ...
class DcString(ModdleElement): ...

class DiDiagram(ModdleElement):
    id: str
    rootElement: DiDiagramElement
    name: str
    documentation: str
    resolution: float
    ownedStyle: list[DiStyle]

class DiDiagramElement(ModdleElement):
    id: str
    extension: DiExtension
    owningDiagram: DiDiagram
    owningElement: DiDiagramElement
    modelElement: ModdleElement
    style: DiStyle
    ownedElement: list[DiDiagramElement]

class DiEdge(DiDiagramElement):
    source: DiDiagramElement
    target: DiDiagramElement
    waypoint: list[DcPoint]

class DiExtension(ModdleElement):
    values: list[ModdleElement]

class DiLabel(DiNode):
    bounds: DcBounds

class DiLabeledEdge(DiEdge):
    ownedLabel: list[DiLabel]

class DiLabeledShape(DiShape):
    ownedLabel: list[DiLabel]

class DiNode(DiDiagramElement): ...

class DiPlane(DiNode):
    planeElement: list[DiDiagramElement]

class DiShape(DiNode):
    bounds: DcBounds

class DiStyle(ModdleElement):
    id: str

class TypedBpmnModdle(BpmnModdle):
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Activity"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnActivity: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:AdHocSubProcess"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnAdHocSubProcess: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Artifact"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnArtifact: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Assignment"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnAssignment: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Association"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnAssociation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Auditing"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnAuditing: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:BaseElement"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnBaseElement: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:BoundaryEvent"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnBoundaryEvent: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:BusinessRuleTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnBusinessRuleTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CallActivity"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCallActivity: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CallChoreography"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCallChoreography: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CallConversation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCallConversation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CallableElement"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCallableElement: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CancelEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCancelEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CatchEvent"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCatchEvent: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Category"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCategory: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CategoryValue"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCategoryValue: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Choreography"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnChoreography: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ChoreographyActivity"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnChoreographyActivity: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ChoreographyTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnChoreographyTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Collaboration"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCollaboration: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CompensateEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCompensateEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ComplexBehaviorDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnComplexBehaviorDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ComplexGateway"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnComplexGateway: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ConditionalEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnConditionalEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Conversation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnConversation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ConversationAssociation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnConversationAssociation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ConversationLink"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnConversationLink: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ConversationNode"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnConversationNode: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CorrelationKey"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCorrelationKey: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CorrelationProperty"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCorrelationProperty: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CorrelationPropertyBinding"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCorrelationPropertyBinding: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CorrelationPropertyRetrievalExpression"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCorrelationPropertyRetrievalExpression: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:CorrelationSubscription"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnCorrelationSubscription: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataAssociation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataAssociation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataInput"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataInput: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataInputAssociation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataInputAssociation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataObject"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataObject: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataObjectReference"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataObjectReference: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataOutput"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataOutput: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataOutputAssociation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataOutputAssociation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataState"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataState: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataStore"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataStore: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:DataStoreReference"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDataStoreReference: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Definitions"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDefinitions: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Documentation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnDocumentation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:EndEvent"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnEndEvent: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:EndPoint"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnEndPoint: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Error"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnError: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ErrorEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnErrorEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Escalation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnEscalation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:EscalationEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnEscalationEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Event"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnEvent: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:EventBasedGateway"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnEventBasedGateway: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:EventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ExclusiveGateway"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnExclusiveGateway: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Expression"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnExpression: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Extension"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnExtension: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ExtensionAttributeDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnExtensionAttributeDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ExtensionDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnExtensionDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ExtensionElements"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnExtensionElements: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:FlowElement"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnFlowElement: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:FlowElementsContainer"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnFlowElementsContainer: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:FlowNode"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnFlowNode: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:FormalExpression"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnFormalExpression: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Gateway"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnGateway: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:GlobalBusinessRuleTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnGlobalBusinessRuleTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:GlobalChoreographyTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnGlobalChoreographyTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:GlobalConversation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnGlobalConversation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:GlobalManualTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnGlobalManualTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:GlobalScriptTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnGlobalScriptTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:GlobalTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnGlobalTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:GlobalUserTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnGlobalUserTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Group"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnGroup: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:HumanPerformer"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnHumanPerformer: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ImplicitThrowEvent"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnImplicitThrowEvent: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Import"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnImport: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:InclusiveGateway"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnInclusiveGateway: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:InputOutputBinding"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnInputOutputBinding: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:InputOutputSpecification"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnInputOutputSpecification: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:InputSet"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnInputSet: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:InteractionNode"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnInteractionNode: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Interface"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnInterface: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:IntermediateCatchEvent"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnIntermediateCatchEvent: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:IntermediateThrowEvent"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnIntermediateThrowEvent: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ItemAwareElement"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnItemAwareElement: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ItemDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnItemDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Lane"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnLane: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:LaneSet"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnLaneSet: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:LinkEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnLinkEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:LoopCharacteristics"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnLoopCharacteristics: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ManualTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnManualTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Message"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnMessage: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:MessageEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnMessageEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:MessageFlow"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnMessageFlow: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:MessageFlowAssociation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnMessageFlowAssociation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Monitoring"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnMonitoring: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:MultiInstanceLoopCharacteristics"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnMultiInstanceLoopCharacteristics: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Operation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnOperation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:OutputSet"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnOutputSet: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ParallelGateway"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnParallelGateway: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Participant"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnParticipant: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ParticipantAssociation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnParticipantAssociation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ParticipantMultiplicity"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnParticipantMultiplicity: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:PartnerEntity"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnPartnerEntity: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:PartnerRole"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnPartnerRole: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Performer"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnPerformer: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:PotentialOwner"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnPotentialOwner: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Process"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnProcess: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Property"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnProperty: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ReceiveTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnReceiveTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Relationship"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnRelationship: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Rendering"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnRendering: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Resource"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnResource: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ResourceAssignmentExpression"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnResourceAssignmentExpression: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ResourceParameter"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnResourceParameter: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ResourceParameterBinding"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnResourceParameterBinding: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ResourceRole"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnResourceRole: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:RootElement"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnRootElement: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ScriptTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnScriptTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:SendTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnSendTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:SequenceFlow"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnSequenceFlow: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ServiceTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnServiceTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Signal"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnSignal: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:SignalEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnSignalEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:StandardLoopCharacteristics"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnStandardLoopCharacteristics: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:StartEvent"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnStartEvent: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:SubChoreography"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnSubChoreography: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:SubConversation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnSubConversation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:SubProcess"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnSubProcess: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Task"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:TerminateEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnTerminateEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:TextAnnotation"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnTextAnnotation: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:ThrowEvent"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnThrowEvent: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:TimerEventDefinition"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnTimerEventDefinition: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:Transaction"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnTransaction: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmn:UserTask"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmnUserTask: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmndi:BPMNDiagram"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmndiBPMNDiagram: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmndi:BPMNEdge"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmndiBPMNEdge: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmndi:BPMNLabel"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmndiBPMNLabel: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmndi:BPMNLabelStyle"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmndiBPMNLabelStyle: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmndi:BPMNPlane"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmndiBPMNPlane: ...
    @overload
    def create(
        self,
        descriptor: Literal["bpmndi:BPMNShape"],
        attrs: dict[str, Any] | None = ...,
    ) -> BpmndiBPMNShape: ...
    @overload
    def create(
        self,
        descriptor: Literal["dc:Boolean"],
        attrs: dict[str, Any] | None = ...,
    ) -> DcBoolean: ...
    @overload
    def create(
        self,
        descriptor: Literal["dc:Bounds"],
        attrs: dict[str, Any] | None = ...,
    ) -> DcBounds: ...
    @overload
    def create(
        self,
        descriptor: Literal["dc:Font"],
        attrs: dict[str, Any] | None = ...,
    ) -> DcFont: ...
    @overload
    def create(
        self,
        descriptor: Literal["dc:Integer"],
        attrs: dict[str, Any] | None = ...,
    ) -> DcInteger: ...
    @overload
    def create(
        self,
        descriptor: Literal["dc:Point"],
        attrs: dict[str, Any] | None = ...,
    ) -> DcPoint: ...
    @overload
    def create(
        self,
        descriptor: Literal["dc:Real"],
        attrs: dict[str, Any] | None = ...,
    ) -> DcReal: ...
    @overload
    def create(
        self,
        descriptor: Literal["dc:String"],
        attrs: dict[str, Any] | None = ...,
    ) -> DcString: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:Diagram"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiDiagram: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:DiagramElement"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiDiagramElement: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:Edge"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiEdge: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:Extension"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiExtension: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:Label"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiLabel: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:LabeledEdge"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiLabeledEdge: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:LabeledShape"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiLabeledShape: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:Node"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiNode: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:Plane"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiPlane: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:Shape"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiShape: ...
    @overload
    def create(
        self,
        descriptor: Literal["di:Style"],
        attrs: dict[str, Any] | None = ...,
    ) -> DiStyle: ...
    @overload
    def create(
        self,
        descriptor: str | EffectiveDescriptor,
        attrs: dict[str, Any] | None = ...,
    ) -> ModdleElement: ...

@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Activity"],
) -> TypeGuard[BpmnActivity]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:AdHocSubProcess"],
) -> TypeGuard[BpmnAdHocSubProcess]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Artifact"],
) -> TypeGuard[BpmnArtifact]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Assignment"],
) -> TypeGuard[BpmnAssignment]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Association"],
) -> TypeGuard[BpmnAssociation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Auditing"],
) -> TypeGuard[BpmnAuditing]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:BaseElement"],
) -> TypeGuard[BpmnBaseElement]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:BoundaryEvent"],
) -> TypeGuard[BpmnBoundaryEvent]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:BusinessRuleTask"],
) -> TypeGuard[BpmnBusinessRuleTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CallActivity"],
) -> TypeGuard[BpmnCallActivity]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CallChoreography"],
) -> TypeGuard[BpmnCallChoreography]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CallConversation"],
) -> TypeGuard[BpmnCallConversation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CallableElement"],
) -> TypeGuard[BpmnCallableElement]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CancelEventDefinition"],
) -> TypeGuard[BpmnCancelEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CatchEvent"],
) -> TypeGuard[BpmnCatchEvent]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Category"],
) -> TypeGuard[BpmnCategory]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CategoryValue"],
) -> TypeGuard[BpmnCategoryValue]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Choreography"],
) -> TypeGuard[BpmnChoreography]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ChoreographyActivity"],
) -> TypeGuard[BpmnChoreographyActivity]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ChoreographyTask"],
) -> TypeGuard[BpmnChoreographyTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Collaboration"],
) -> TypeGuard[BpmnCollaboration]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CompensateEventDefinition"],
) -> TypeGuard[BpmnCompensateEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ComplexBehaviorDefinition"],
) -> TypeGuard[BpmnComplexBehaviorDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ComplexGateway"],
) -> TypeGuard[BpmnComplexGateway]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ConditionalEventDefinition"],
) -> TypeGuard[BpmnConditionalEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Conversation"],
) -> TypeGuard[BpmnConversation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ConversationAssociation"],
) -> TypeGuard[BpmnConversationAssociation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ConversationLink"],
) -> TypeGuard[BpmnConversationLink]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ConversationNode"],
) -> TypeGuard[BpmnConversationNode]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CorrelationKey"],
) -> TypeGuard[BpmnCorrelationKey]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CorrelationProperty"],
) -> TypeGuard[BpmnCorrelationProperty]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CorrelationPropertyBinding"],
) -> TypeGuard[BpmnCorrelationPropertyBinding]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CorrelationPropertyRetrievalExpression"],
) -> TypeGuard[BpmnCorrelationPropertyRetrievalExpression]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:CorrelationSubscription"],
) -> TypeGuard[BpmnCorrelationSubscription]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataAssociation"],
) -> TypeGuard[BpmnDataAssociation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataInput"],
) -> TypeGuard[BpmnDataInput]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataInputAssociation"],
) -> TypeGuard[BpmnDataInputAssociation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataObject"],
) -> TypeGuard[BpmnDataObject]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataObjectReference"],
) -> TypeGuard[BpmnDataObjectReference]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataOutput"],
) -> TypeGuard[BpmnDataOutput]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataOutputAssociation"],
) -> TypeGuard[BpmnDataOutputAssociation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataState"],
) -> TypeGuard[BpmnDataState]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataStore"],
) -> TypeGuard[BpmnDataStore]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:DataStoreReference"],
) -> TypeGuard[BpmnDataStoreReference]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Definitions"],
) -> TypeGuard[BpmnDefinitions]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Documentation"],
) -> TypeGuard[BpmnDocumentation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:EndEvent"],
) -> TypeGuard[BpmnEndEvent]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:EndPoint"],
) -> TypeGuard[BpmnEndPoint]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Error"],
) -> TypeGuard[BpmnError]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ErrorEventDefinition"],
) -> TypeGuard[BpmnErrorEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Escalation"],
) -> TypeGuard[BpmnEscalation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:EscalationEventDefinition"],
) -> TypeGuard[BpmnEscalationEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Event"],
) -> TypeGuard[BpmnEvent]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:EventBasedGateway"],
) -> TypeGuard[BpmnEventBasedGateway]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:EventDefinition"],
) -> TypeGuard[BpmnEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ExclusiveGateway"],
) -> TypeGuard[BpmnExclusiveGateway]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Expression"],
) -> TypeGuard[BpmnExpression]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Extension"],
) -> TypeGuard[BpmnExtension]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ExtensionAttributeDefinition"],
) -> TypeGuard[BpmnExtensionAttributeDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ExtensionDefinition"],
) -> TypeGuard[BpmnExtensionDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ExtensionElements"],
) -> TypeGuard[BpmnExtensionElements]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:FlowElement"],
) -> TypeGuard[BpmnFlowElement]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:FlowElementsContainer"],
) -> TypeGuard[BpmnFlowElementsContainer]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:FlowNode"],
) -> TypeGuard[BpmnFlowNode]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:FormalExpression"],
) -> TypeGuard[BpmnFormalExpression]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Gateway"],
) -> TypeGuard[BpmnGateway]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:GlobalBusinessRuleTask"],
) -> TypeGuard[BpmnGlobalBusinessRuleTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:GlobalChoreographyTask"],
) -> TypeGuard[BpmnGlobalChoreographyTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:GlobalConversation"],
) -> TypeGuard[BpmnGlobalConversation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:GlobalManualTask"],
) -> TypeGuard[BpmnGlobalManualTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:GlobalScriptTask"],
) -> TypeGuard[BpmnGlobalScriptTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:GlobalTask"],
) -> TypeGuard[BpmnGlobalTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:GlobalUserTask"],
) -> TypeGuard[BpmnGlobalUserTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Group"],
) -> TypeGuard[BpmnGroup]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:HumanPerformer"],
) -> TypeGuard[BpmnHumanPerformer]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ImplicitThrowEvent"],
) -> TypeGuard[BpmnImplicitThrowEvent]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Import"],
) -> TypeGuard[BpmnImport]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:InclusiveGateway"],
) -> TypeGuard[BpmnInclusiveGateway]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:InputOutputBinding"],
) -> TypeGuard[BpmnInputOutputBinding]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:InputOutputSpecification"],
) -> TypeGuard[BpmnInputOutputSpecification]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:InputSet"],
) -> TypeGuard[BpmnInputSet]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:InteractionNode"],
) -> TypeGuard[BpmnInteractionNode]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Interface"],
) -> TypeGuard[BpmnInterface]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:IntermediateCatchEvent"],
) -> TypeGuard[BpmnIntermediateCatchEvent]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:IntermediateThrowEvent"],
) -> TypeGuard[BpmnIntermediateThrowEvent]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ItemAwareElement"],
) -> TypeGuard[BpmnItemAwareElement]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ItemDefinition"],
) -> TypeGuard[BpmnItemDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Lane"],
) -> TypeGuard[BpmnLane]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:LaneSet"],
) -> TypeGuard[BpmnLaneSet]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:LinkEventDefinition"],
) -> TypeGuard[BpmnLinkEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:LoopCharacteristics"],
) -> TypeGuard[BpmnLoopCharacteristics]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ManualTask"],
) -> TypeGuard[BpmnManualTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Message"],
) -> TypeGuard[BpmnMessage]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:MessageEventDefinition"],
) -> TypeGuard[BpmnMessageEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:MessageFlow"],
) -> TypeGuard[BpmnMessageFlow]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:MessageFlowAssociation"],
) -> TypeGuard[BpmnMessageFlowAssociation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Monitoring"],
) -> TypeGuard[BpmnMonitoring]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:MultiInstanceLoopCharacteristics"],
) -> TypeGuard[BpmnMultiInstanceLoopCharacteristics]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Operation"],
) -> TypeGuard[BpmnOperation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:OutputSet"],
) -> TypeGuard[BpmnOutputSet]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ParallelGateway"],
) -> TypeGuard[BpmnParallelGateway]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Participant"],
) -> TypeGuard[BpmnParticipant]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ParticipantAssociation"],
) -> TypeGuard[BpmnParticipantAssociation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ParticipantMultiplicity"],
) -> TypeGuard[BpmnParticipantMultiplicity]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:PartnerEntity"],
) -> TypeGuard[BpmnPartnerEntity]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:PartnerRole"],
) -> TypeGuard[BpmnPartnerRole]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Performer"],
) -> TypeGuard[BpmnPerformer]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:PotentialOwner"],
) -> TypeGuard[BpmnPotentialOwner]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Process"],
) -> TypeGuard[BpmnProcess]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Property"],
) -> TypeGuard[BpmnProperty]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ReceiveTask"],
) -> TypeGuard[BpmnReceiveTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Relationship"],
) -> TypeGuard[BpmnRelationship]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Rendering"],
) -> TypeGuard[BpmnRendering]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Resource"],
) -> TypeGuard[BpmnResource]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ResourceAssignmentExpression"],
) -> TypeGuard[BpmnResourceAssignmentExpression]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ResourceParameter"],
) -> TypeGuard[BpmnResourceParameter]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ResourceParameterBinding"],
) -> TypeGuard[BpmnResourceParameterBinding]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ResourceRole"],
) -> TypeGuard[BpmnResourceRole]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:RootElement"],
) -> TypeGuard[BpmnRootElement]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ScriptTask"],
) -> TypeGuard[BpmnScriptTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:SendTask"],
) -> TypeGuard[BpmnSendTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:SequenceFlow"],
) -> TypeGuard[BpmnSequenceFlow]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ServiceTask"],
) -> TypeGuard[BpmnServiceTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Signal"],
) -> TypeGuard[BpmnSignal]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:SignalEventDefinition"],
) -> TypeGuard[BpmnSignalEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:StandardLoopCharacteristics"],
) -> TypeGuard[BpmnStandardLoopCharacteristics]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:StartEvent"],
) -> TypeGuard[BpmnStartEvent]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:SubChoreography"],
) -> TypeGuard[BpmnSubChoreography]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:SubConversation"],
) -> TypeGuard[BpmnSubConversation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:SubProcess"],
) -> TypeGuard[BpmnSubProcess]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Task"],
) -> TypeGuard[BpmnTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:TerminateEventDefinition"],
) -> TypeGuard[BpmnTerminateEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:TextAnnotation"],
) -> TypeGuard[BpmnTextAnnotation]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:ThrowEvent"],
) -> TypeGuard[BpmnThrowEvent]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:TimerEventDefinition"],
) -> TypeGuard[BpmnTimerEventDefinition]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:Transaction"],
) -> TypeGuard[BpmnTransaction]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmn:UserTask"],
) -> TypeGuard[BpmnUserTask]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmndi:BPMNDiagram"],
) -> TypeGuard[BpmndiBPMNDiagram]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmndi:BPMNEdge"],
) -> TypeGuard[BpmndiBPMNEdge]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmndi:BPMNLabel"],
) -> TypeGuard[BpmndiBPMNLabel]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmndi:BPMNLabelStyle"],
) -> TypeGuard[BpmndiBPMNLabelStyle]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmndi:BPMNPlane"],
) -> TypeGuard[BpmndiBPMNPlane]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["bpmndi:BPMNShape"],
) -> TypeGuard[BpmndiBPMNShape]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["dc:Boolean"],
) -> TypeGuard[DcBoolean]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["dc:Bounds"],
) -> TypeGuard[DcBounds]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["dc:Font"],
) -> TypeGuard[DcFont]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["dc:Integer"],
) -> TypeGuard[DcInteger]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["dc:Point"],
) -> TypeGuard[DcPoint]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["dc:Real"],
) -> TypeGuard[DcReal]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["dc:String"],
) -> TypeGuard[DcString]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:Diagram"],
) -> TypeGuard[DiDiagram]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:DiagramElement"],
) -> TypeGuard[DiDiagramElement]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:Edge"],
) -> TypeGuard[DiEdge]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:Extension"],
) -> TypeGuard[DiExtension]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:Label"],
) -> TypeGuard[DiLabel]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:LabeledEdge"],
) -> TypeGuard[DiLabeledEdge]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:LabeledShape"],
) -> TypeGuard[DiLabeledShape]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:Node"],
) -> TypeGuard[DiNode]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:Plane"],
) -> TypeGuard[DiPlane]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:Shape"],
) -> TypeGuard[DiShape]: ...
@overload
def is_a(
    element: object,
    type_name: Literal["di:Style"],
) -> TypeGuard[DiStyle]: ...
@overload
def is_a(
    element: object,
    type_name: str,
) -> TypeGuard[ModdleElement]: ...
