#!/usr/bin/env python3
"""Generate the typed creation surface for the default BPMN model.

Usage:
  scripts/gen_stubs.py            # regenerate src/bpmn_io/bpmn_moddle/types.pyi
  scripts/gen_stubs.py --check    # exit 1 when the committed stub drifts (CI)
  scripts/gen_stubs.py --json     # print the generated files as JSON

Reads the six vendored descriptors through bpmn_io.descriptors.DESCRIPTOR_NAMES
(read-only, never written); the generated stub is committed (LEDGER.json
precedent). stdlib only.
"""

from __future__ import annotations

import json
import keyword
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from bpmn_io.descriptors import DESCRIPTOR_NAMES  # noqa: E402

STUB = ROOT / "src" / "bpmn_io" / "bpmn_moddle" / "types.pyi"

#: Descriptor primitive -> stub annotation.
PRIMITIVES = {
    "String": "str",
    "Boolean": "bool",
    "Integer": "int",
    "Real": "float",
    "Element": "ModdleElement",
}

#: Valid stub attribute names (keyword-named properties use get/set instead).
NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

#: Stub class names that would shadow the stub's own imports.
RESERVED = frozenset(
    {
        "Any",
        "BpmnModdle",
        "BpmnTypeName",
        "EffectiveDescriptor",
        "Literal",
        "ModdleElement",
        "TypeGuard",
        "TypedBpmnModdle",
        "overload",
    }
)


def cap(name: str) -> str:
    """Capitalize one package prefix (bpmn -> Bpmn)."""
    return name[:1].upper() + name[1:]


def class_name(package: str, local: str) -> str:
    """Map a descriptor type to its stub class name (fail loudly on garbage)."""
    base = re.sub(r"[^0-9A-Za-z_]", "", local)
    if not base or base[0].isdigit() or keyword.iskeyword(base):
        msg = f"gen_stubs: cannot map type {package}:{local} to a class name"
        raise SystemExit(msg)
    name = cap(package) + base
    if name in RESERVED:
        msg = f"gen_stubs: class-name collision: {package}:{local} maps to reserved {name!r}"
        raise SystemExit(msg)
    return name


def qualname(package: str, raw: str) -> str:
    """Resolve a descriptor-local reference the way the registry does."""
    return raw if ":" in raw else f"{package}:{raw}"


def collect() -> tuple[list[dict[str, object]], set[str], int]:
    """Return (concrete types, enumeration qualnames, skipped trait count)."""
    concrete: list[dict[str, object]] = []
    enums: set[str] = set()
    skipped = 0
    for key, relative in DESCRIPTOR_NAMES.items():
        data = json.loads((ROOT / "src" / "bpmn_io" / "resources" / relative).read_text())
        prefix = str(data.get("prefix") or key)
        for entry in data.get("enumerations") or []:
            name = entry["name"] if isinstance(entry, dict) else entry
            enums.add(f"{prefix}:{name}")
        for type_def in data.get("types") or []:
            if type_def.get("isGeneric") or type_def.get("extends"):
                skipped += 1
                continue
            local = str(type_def["name"])
            concrete.append(
                {
                    "qual": qualname(prefix, local),
                    "package": prefix,
                    "local": local,
                    "class": class_name(prefix, local),
                    "supers": [qualname(prefix, s) for s in type_def.get("superClass") or []],
                    "properties": list(type_def.get("properties") or []),
                }
            )
    seen: dict[str, str] = {}
    for info in concrete:
        name = str(info["class"])
        if name in seen and seen[name] != info["qual"]:
            msg = f"gen_stubs: collision: {seen[name]} and {info['qual']} map to {name!r}"
            raise SystemExit(msg)
        seen[name] = str(info["qual"])
    concrete.sort(key=lambda info: str(info["qual"]))
    return concrete, enums, skipped


def annotation(
    raw: str,
    package: str,
    by_qual: dict[str, str],
    enums: set[str],
    *,
    is_many: bool,
) -> str:
    """Map a descriptor property type to a stub annotation (Any when unknown)."""
    local = raw.rsplit(":", maxsplit=1)[-1]
    if local in PRIMITIVES:
        base = PRIMITIVES[local]
    else:
        qualified = qualname(package, raw)
        if qualified in enums or (":" not in raw and qualified in enums):
            base = "str"
        else:
            base = by_qual.get(qualified, "Any")
    return f"list[{base}]" if is_many else base


def emit(concrete: list[dict[str, object]], enums: set[str], skipped: int) -> str:
    """Render the full stub text."""
    by_qual = {str(info["qual"]): str(info["class"]) for info in concrete}
    lines = [
        "# Generated by scripts/gen_stubs.py: do not edit.",
        "#",
        "# Typed view over the default six-package BPMN model: one class per",
        "# concrete descriptor type (Cap(prefix) + local name, e.g. bpmn:Task",
        "# becomes BpmnTask), Literal-typed create() overloads on",
        "# TypedBpmnModdle, and TypeGuard-typed is_a() overloads. Elements are",
        "# created dynamically by the model factory, so these classes have no",
        "# runtime behavior; keyword-named properties (from, import) are omitted",
        f"# (reachable via get/set). {len(concrete)} types; {skipped} traits skipped.",
        "# Descriptor property names stay camelCase by contract, hence the",
        "# file-wide N815 exemption.",
        "# ruff: noqa: N815",
        "",
        "from typing import Any, Literal, TypeAlias, TypeGuard, overload",
        "",
        "from bpmn_io.bpmn_moddle.bpmn_moddle import BpmnModdle",
        "from bpmn_io.moddle.base import ModdleElement",
        "from bpmn_io.moddle.descriptor_builder import EffectiveDescriptor",
        "",
        "BpmnTypeName: TypeAlias = Literal[",
    ]
    lines.extend(f'    "{info["qual"]}",' for info in concrete)
    lines.append("]")
    lines.append("")
    blocks: list[list[str]] = []
    for info in concrete:
        supers = [by_qual[s] for s in info["supers"] if s in by_qual]
        bases = ", ".join(supers) if supers else "ModdleElement"
        props = [
            p
            for p in info["properties"]
            if NAME_RE.match(p["name"]) and not keyword.iskeyword(p["name"])
        ]
        if not props:
            blocks.append([f"class {info['class']}({bases}): ..."])
            continue
        block = [f"class {info['class']}({bases}):"]
        for prop in props:
            ann = annotation(
                prop["type"],
                str(info["package"]),
                by_qual,
                enums,
                is_many=bool(prop.get("isMany")),
            )
            block.append(f"    {prop['name']}: {ann}")
        blocks.append(block)
    for index, block in enumerate(blocks):
        if index and (len(block) > 1 or len(blocks[index - 1]) > 1):
            lines.append("")
        lines.extend(block)
    lines.append("")
    lines.append("class TypedBpmnModdle(BpmnModdle):")
    for info in concrete:
        lines.append("    @overload")
        lines.append("    def create(")
        lines.append("        self,")
        lines.append(f'        descriptor: Literal["{info["qual"]}"],')
        lines.append("        attrs: dict[str, Any] | None = ...,")
        lines.append(f"    ) -> {info['class']}: ...")
    lines.append("    @overload")
    lines.append("    def create(")
    lines.append("        self,")
    lines.append("        descriptor: str | EffectiveDescriptor,")
    lines.append("        attrs: dict[str, Any] | None = ...,")
    lines.append("    ) -> ModdleElement: ...")
    lines.append("")
    for info in concrete:
        lines.append("@overload")
        lines.append("def is_a(")
        lines.append("    element: object,")
        lines.append(f'    type_name: Literal["{info["qual"]}"],')
        lines.append(f") -> TypeGuard[{info['class']}]: ...")
    lines.append("@overload")
    lines.append("def is_a(")
    lines.append("    element: object,")
    lines.append("    type_name: str,")
    lines.append(") -> TypeGuard[ModdleElement]: ...")
    return "\n".join(lines) + "\n"


def render() -> tuple[str, list[str]]:
    """Return (stub text, sorted concrete qualnames)."""
    concrete, enums, skipped = collect()
    return emit(concrete, enums, skipped), sorted(str(info["qual"]) for info in concrete)


def main(argv: list[str]) -> int:
    """Regenerate the stub (default), check drift (--check), or list (--json)."""
    check = "--check" in argv
    as_json = "--json" in argv
    rest = [a for a in argv if a not in ("--check", "--json")]
    if rest:
        print(__doc__)
        return 2
    text, _quals = render()
    relative = str(STUB.relative_to(ROOT))
    if check:
        current = STUB.read_text(encoding="utf-8") if STUB.exists() else ""
        if current != text:
            print(f"DRIFT    {relative} (run scripts/gen_stubs.py to regenerate)")
            if as_json:
                print(json.dumps({"files": [relative], "drift": True}, indent=2))
            return 1
        if as_json:
            print(json.dumps({"files": [relative], "drift": False}, indent=2))
        else:
            print("ok")
        return 0
    STUB.write_text(text, encoding="utf-8")
    if as_json:
        print(json.dumps({"files": [relative]}, indent=2))
    else:
        print(f"wrote {relative}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
